/// Flutter icons Google
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Google
///      fonts:
///       - asset: fonts/Google.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Google {
  Google._();

  static const _kFontFam = 'Google';
  static const _kFontFb = 'Facebook';

  static const String? _kFontPkg = null;

  static const IconData gplus =
      IconData(0xf0d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_squared =
      IconData(0xf30e, fontFamily: _kFontFb, fontPackage: _kFontPkg);
}
